//! Generated independent test oracle. DO NOT EDIT.
//! Source: Unicode 17.0.0 UnicodeData.txt, SHA-256 2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
//! Scope comes from the finite implementation switches; answers come from Unicode data
//! plus documented house overrides for stroke letters, Romanian legacy forms, ligatures,
//! ASCII fraction slash, and U+2180.

pub const Fold = struct { cp: u21, base: u8, dia: u8, upper: bool };
pub const Expansion = struct { cp: u21, replacement: []const u8 };

pub const folds = [_]Fold{
    .{ .cp = 0xC0, .base = 'a', .dia = 1, .upper = true },
    .{ .cp = 0xC1, .base = 'a', .dia = 2, .upper = true },
    .{ .cp = 0xC2, .base = 'a', .dia = 3, .upper = true },
    .{ .cp = 0xC3, .base = 'a', .dia = 4, .upper = true },
    .{ .cp = 0xC4, .base = 'a', .dia = 5, .upper = true },
    .{ .cp = 0xC5, .base = 'a', .dia = 6, .upper = true },
    .{ .cp = 0xC7, .base = 'c', .dia = 7, .upper = true },
    .{ .cp = 0xC8, .base = 'e', .dia = 1, .upper = true },
    .{ .cp = 0xC9, .base = 'e', .dia = 2, .upper = true },
    .{ .cp = 0xCA, .base = 'e', .dia = 3, .upper = true },
    .{ .cp = 0xCB, .base = 'e', .dia = 5, .upper = true },
    .{ .cp = 0xCC, .base = 'i', .dia = 1, .upper = true },
    .{ .cp = 0xCD, .base = 'i', .dia = 2, .upper = true },
    .{ .cp = 0xCE, .base = 'i', .dia = 3, .upper = true },
    .{ .cp = 0xCF, .base = 'i', .dia = 5, .upper = true },
    .{ .cp = 0xD1, .base = 'n', .dia = 4, .upper = true },
    .{ .cp = 0xD2, .base = 'o', .dia = 1, .upper = true },
    .{ .cp = 0xD3, .base = 'o', .dia = 2, .upper = true },
    .{ .cp = 0xD4, .base = 'o', .dia = 3, .upper = true },
    .{ .cp = 0xD5, .base = 'o', .dia = 4, .upper = true },
    .{ .cp = 0xD6, .base = 'o', .dia = 5, .upper = true },
    .{ .cp = 0xD8, .base = 'o', .dia = 11, .upper = true },
    .{ .cp = 0xD9, .base = 'u', .dia = 1, .upper = true },
    .{ .cp = 0xDA, .base = 'u', .dia = 2, .upper = true },
    .{ .cp = 0xDB, .base = 'u', .dia = 3, .upper = true },
    .{ .cp = 0xDC, .base = 'u', .dia = 5, .upper = true },
    .{ .cp = 0xDD, .base = 'y', .dia = 2, .upper = true },
    .{ .cp = 0xE0, .base = 'a', .dia = 1, .upper = false },
    .{ .cp = 0xE1, .base = 'a', .dia = 2, .upper = false },
    .{ .cp = 0xE2, .base = 'a', .dia = 3, .upper = false },
    .{ .cp = 0xE3, .base = 'a', .dia = 4, .upper = false },
    .{ .cp = 0xE4, .base = 'a', .dia = 5, .upper = false },
    .{ .cp = 0xE5, .base = 'a', .dia = 6, .upper = false },
    .{ .cp = 0xE7, .base = 'c', .dia = 7, .upper = false },
    .{ .cp = 0xE8, .base = 'e', .dia = 1, .upper = false },
    .{ .cp = 0xE9, .base = 'e', .dia = 2, .upper = false },
    .{ .cp = 0xEA, .base = 'e', .dia = 3, .upper = false },
    .{ .cp = 0xEB, .base = 'e', .dia = 5, .upper = false },
    .{ .cp = 0xEC, .base = 'i', .dia = 1, .upper = false },
    .{ .cp = 0xED, .base = 'i', .dia = 2, .upper = false },
    .{ .cp = 0xEE, .base = 'i', .dia = 3, .upper = false },
    .{ .cp = 0xEF, .base = 'i', .dia = 5, .upper = false },
    .{ .cp = 0xF1, .base = 'n', .dia = 4, .upper = false },
    .{ .cp = 0xF2, .base = 'o', .dia = 1, .upper = false },
    .{ .cp = 0xF3, .base = 'o', .dia = 2, .upper = false },
    .{ .cp = 0xF4, .base = 'o', .dia = 3, .upper = false },
    .{ .cp = 0xF5, .base = 'o', .dia = 4, .upper = false },
    .{ .cp = 0xF6, .base = 'o', .dia = 5, .upper = false },
    .{ .cp = 0xF8, .base = 'o', .dia = 11, .upper = false },
    .{ .cp = 0xF9, .base = 'u', .dia = 1, .upper = false },
    .{ .cp = 0xFA, .base = 'u', .dia = 2, .upper = false },
    .{ .cp = 0xFB, .base = 'u', .dia = 3, .upper = false },
    .{ .cp = 0xFC, .base = 'u', .dia = 5, .upper = false },
    .{ .cp = 0xFD, .base = 'y', .dia = 2, .upper = false },
    .{ .cp = 0xFF, .base = 'y', .dia = 5, .upper = false },
    .{ .cp = 0x100, .base = 'a', .dia = 9, .upper = true },
    .{ .cp = 0x101, .base = 'a', .dia = 9, .upper = false },
    .{ .cp = 0x102, .base = 'a', .dia = 12, .upper = true },
    .{ .cp = 0x103, .base = 'a', .dia = 12, .upper = false },
    .{ .cp = 0x106, .base = 'c', .dia = 2, .upper = true },
    .{ .cp = 0x107, .base = 'c', .dia = 2, .upper = false },
    .{ .cp = 0x10C, .base = 'c', .dia = 8, .upper = true },
    .{ .cp = 0x10D, .base = 'c', .dia = 8, .upper = false },
    .{ .cp = 0x110, .base = 'd', .dia = 11, .upper = true },
    .{ .cp = 0x111, .base = 'd', .dia = 11, .upper = false },
    .{ .cp = 0x112, .base = 'e', .dia = 9, .upper = true },
    .{ .cp = 0x113, .base = 'e', .dia = 9, .upper = false },
    .{ .cp = 0x11A, .base = 'e', .dia = 8, .upper = true },
    .{ .cp = 0x11B, .base = 'e', .dia = 8, .upper = false },
    .{ .cp = 0x12A, .base = 'i', .dia = 9, .upper = true },
    .{ .cp = 0x12B, .base = 'i', .dia = 9, .upper = false },
    .{ .cp = 0x13F, .base = 'l', .dia = 14, .upper = true },
    .{ .cp = 0x140, .base = 'l', .dia = 14, .upper = false },
    .{ .cp = 0x141, .base = 'l', .dia = 11, .upper = true },
    .{ .cp = 0x142, .base = 'l', .dia = 11, .upper = false },
    .{ .cp = 0x143, .base = 'n', .dia = 2, .upper = true },
    .{ .cp = 0x144, .base = 'n', .dia = 2, .upper = false },
    .{ .cp = 0x147, .base = 'n', .dia = 8, .upper = true },
    .{ .cp = 0x148, .base = 'n', .dia = 8, .upper = false },
    .{ .cp = 0x14C, .base = 'o', .dia = 9, .upper = true },
    .{ .cp = 0x14D, .base = 'o', .dia = 9, .upper = false },
    .{ .cp = 0x158, .base = 'r', .dia = 8, .upper = true },
    .{ .cp = 0x159, .base = 'r', .dia = 8, .upper = false },
    .{ .cp = 0x15A, .base = 's', .dia = 2, .upper = true },
    .{ .cp = 0x15B, .base = 's', .dia = 2, .upper = false },
    .{ .cp = 0x15E, .base = 's', .dia = 13, .upper = true },
    .{ .cp = 0x15F, .base = 's', .dia = 13, .upper = false },
    .{ .cp = 0x160, .base = 's', .dia = 8, .upper = true },
    .{ .cp = 0x161, .base = 's', .dia = 8, .upper = false },
    .{ .cp = 0x162, .base = 't', .dia = 13, .upper = true },
    .{ .cp = 0x163, .base = 't', .dia = 13, .upper = false },
    .{ .cp = 0x16A, .base = 'u', .dia = 9, .upper = true },
    .{ .cp = 0x16B, .base = 'u', .dia = 9, .upper = false },
    .{ .cp = 0x179, .base = 'z', .dia = 2, .upper = true },
    .{ .cp = 0x17A, .base = 'z', .dia = 2, .upper = false },
    .{ .cp = 0x17B, .base = 'z', .dia = 10, .upper = true },
    .{ .cp = 0x17C, .base = 'z', .dia = 10, .upper = false },
    .{ .cp = 0x17D, .base = 'z', .dia = 8, .upper = true },
    .{ .cp = 0x17E, .base = 'z', .dia = 8, .upper = false },
    .{ .cp = 0x218, .base = 's', .dia = 13, .upper = true },
    .{ .cp = 0x219, .base = 's', .dia = 13, .upper = false },
    .{ .cp = 0x21A, .base = 't', .dia = 13, .upper = true },
    .{ .cp = 0x21B, .base = 't', .dia = 13, .upper = false },
};

pub const expansions = [_]Expansion{
    .{ .cp = 0xBC, .replacement = "1/4" },
    .{ .cp = 0xBD, .replacement = "1/2" },
    .{ .cp = 0xBE, .replacement = "3/4" },
    .{ .cp = 0xC6, .replacement = "AE" },
    .{ .cp = 0xDF, .replacement = "ss" },
    .{ .cp = 0xE6, .replacement = "ae" },
    .{ .cp = 0x132, .replacement = "IJ" },
    .{ .cp = 0x133, .replacement = "ij" },
    .{ .cp = 0x152, .replacement = "OE" },
    .{ .cp = 0x153, .replacement = "oe" },
    .{ .cp = 0x1E9E, .replacement = "SS" },
    .{ .cp = 0x2105, .replacement = "c/o" },
    .{ .cp = 0x2116, .replacement = "No" },
    .{ .cp = 0x2122, .replacement = "TM" },
    .{ .cp = 0x2150, .replacement = "1/7" },
    .{ .cp = 0x2151, .replacement = "1/9" },
    .{ .cp = 0x2152, .replacement = "1/10" },
    .{ .cp = 0x2153, .replacement = "1/3" },
    .{ .cp = 0x2154, .replacement = "2/3" },
    .{ .cp = 0x2155, .replacement = "1/5" },
    .{ .cp = 0x2156, .replacement = "2/5" },
    .{ .cp = 0x2157, .replacement = "3/5" },
    .{ .cp = 0x2158, .replacement = "4/5" },
    .{ .cp = 0x2159, .replacement = "1/6" },
    .{ .cp = 0x215A, .replacement = "5/6" },
    .{ .cp = 0x215B, .replacement = "1/8" },
    .{ .cp = 0x215C, .replacement = "3/8" },
    .{ .cp = 0x215D, .replacement = "5/8" },
    .{ .cp = 0x215E, .replacement = "7/8" },
    .{ .cp = 0x2160, .replacement = "I" },
    .{ .cp = 0x2161, .replacement = "II" },
    .{ .cp = 0x2162, .replacement = "III" },
    .{ .cp = 0x2163, .replacement = "IV" },
    .{ .cp = 0x2164, .replacement = "V" },
    .{ .cp = 0x2165, .replacement = "VI" },
    .{ .cp = 0x2166, .replacement = "VII" },
    .{ .cp = 0x2167, .replacement = "VIII" },
    .{ .cp = 0x2168, .replacement = "IX" },
    .{ .cp = 0x2169, .replacement = "X" },
    .{ .cp = 0x216A, .replacement = "XI" },
    .{ .cp = 0x216B, .replacement = "XII" },
    .{ .cp = 0x216C, .replacement = "L" },
    .{ .cp = 0x216D, .replacement = "C" },
    .{ .cp = 0x216E, .replacement = "D" },
    .{ .cp = 0x216F, .replacement = "M" },
    .{ .cp = 0x2170, .replacement = "i" },
    .{ .cp = 0x2171, .replacement = "ii" },
    .{ .cp = 0x2172, .replacement = "iii" },
    .{ .cp = 0x2173, .replacement = "iv" },
    .{ .cp = 0x2174, .replacement = "v" },
    .{ .cp = 0x2175, .replacement = "vi" },
    .{ .cp = 0x2176, .replacement = "vii" },
    .{ .cp = 0x2177, .replacement = "viii" },
    .{ .cp = 0x2178, .replacement = "ix" },
    .{ .cp = 0x2179, .replacement = "x" },
    .{ .cp = 0x217A, .replacement = "xi" },
    .{ .cp = 0x217B, .replacement = "xii" },
    .{ .cp = 0x217C, .replacement = "l" },
    .{ .cp = 0x217D, .replacement = "c" },
    .{ .cp = 0x217E, .replacement = "d" },
    .{ .cp = 0x217F, .replacement = "m" },
    .{ .cp = 0x2180, .replacement = "M" },
    .{ .cp = 0x2189, .replacement = "0/3" },
};
